# Generated by Django 3.2.22 on 2023-10-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mathematicalformula_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.CharField(max_length=100)),
                ('three_month', models.CharField(max_length=100)),
                ('half_year', models.CharField(max_length=100)),
                ('one_year', models.CharField(max_length=100)),
                ('two_year', models.CharField(max_length=100)),
                ('three_year', models.CharField(max_length=100)),
                ('five_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_year', models.CharField(max_length=100)),
                ('one_year', models.CharField(max_length=100)),
                ('one_to_three_year', models.CharField(max_length=100)),
                ('three_to_five_ysar', models.CharField(max_length=100)),
                ('five_year', models.CharField(max_length=100)),
            ],
        ),
    ]
