# Generated by Django 3.2.22 on 2023-10-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_deposit_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='three_to_five_ysar',
            new_name='three_to_five_year',
        ),
    ]
